# [Info]
site_name: 空谷幽兰  # your site name 显示在左上角
site_url: https://sswfive.github.io/bloghub/  # your site url
site_author: AstonWang # your name
# [UI]
theme:
  name: material
  custom_dir: docs/customize/overrides #覆写路径
  # font: #谷歌字体，自行搜索
  #   text: Bitter  #文本字体
  #   code: Roboto Mono  #代码字体
  # logo: assets/favicon.png #左上角logo，可插入图片链接

  favicon: https://s2.loli.net/2024/04/26/PmRdM9iGnvOJHgu.png  # 网页icon

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
      # primary: blue grey
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue grey # 上方的
      accent: blue # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    # - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - navigation.path #激活导航路径后，每个页面的标题上方都会呈现面包屑导航，这可能会让用户在屏幕较小的设备上访问文档时更容易定位
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - toc.follow
  language: zh # 一些提示性的文字会变成中文

  # icon:
  #   repo: fontawesome/brands/github #右上角图标
  #   logo: logo

copyright: Copyright &copy; 2017~2024 AstonWang/All Rights Reserved. # 左下角的版权声明

extra:
  generator: false #是否删除页脚显示“使用 MkDocs 材料制造”
  social:
    # - icon: fontawesome/brands/x-twitter #联系方式图标 : https://fontawesome.com/ 去这里找图标
    #   link: https://twitter.com/wcowin_
    # - icon: fontawesome/brands/github
    #   link: https://github.com/Wcowin

    # - icon: fontawesome/regular/envelope #联系方式图标
    #   link: mailto:<wangkewen821@gmail.com> #邮件联系方式
    # - icon: fontawesome/brands/bilibili
    #   link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
  analytics:
    provider: google #谷歌分析
    property:

    # 网页底部反馈
  #   feedback:
  #     title: 此页面有帮助吗？
  #     ratings:
  #       - icon: material/thumb-up-outline #图标可自定义
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           谢谢你的反馈！
  #       - icon: material/thumb-down-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # # cookies设置（可选）
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好

plugins:
  - search #搜索配置
  - git-committers:
      enabled: !ENV [CI, false]
      repository: sswfive/bloghub
      branch: main
      exclude:
        - index.md
        - tag.md
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: iso_date
      enable_creation_date: true
      exclude:
        - index.md
        - tag.md
        - liuyanban.md
  - blog: #博客配置
      blog_toc: true
      post_date_format: full # 时间
      post_url_date_format: yyyy/MM/dd
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265 #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" #作者信息
  - tags:
      tags_file: tag.md #分类标签

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

extra_javascript:
  - customize/javascripts/extra.js #自定义javascript
  - customize/javascripts/mathjax.js #Latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6 #Latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latex支持
  # - ckplayer/js/ckplayer.js #播放器配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了

extra_css:
  - customize/stylesheets/extra.css # 自定义CSS
  # - customize/stylesheets/link.css #友链配置
  - customize/stylesheets/customize.css # 搜索圆角优化

  # - stylesheets/video.css #播放器可选配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  # - ckplayer/css/ckplayer.css   #播放器配置
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持

  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字体

edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/sswfive/bloghub # 右上角点击跳转的链接
repo_name: AstonWang # 右上角的名字

# [Navigtion]
nav:
  - 主页: 
    - index.md
    - 关于: about/personal_profile.md
  - Python编程:
    - index: language/python/index.md
    - Python最佳实践:
      - language/python/pybestpractices/py_logger_usage.md
      - language/python/pybestpractices/py_security_guide.md
      - language/python/pybestpractices/docker_build_python_image.md
      - language/python/pybestpractices/py_data_struct_summary.md
      - language/python/pybestpractices/py2_py3_update.md
      - language/python/pybestpractices/coding_standard.md
    - Python Web:
      - language/python/pyweb/django/django_lazyobject_analysis.md
      - language/python/pyweb/django/django_websocket_usage.md
      - language/python/pyweb/django/django_class_view_usage.md
      - language/python/pyweb/django/django_middleware_usage.md
      - language/python/pyweb/django/django_bulk_create.md
      - language/python/pyweb/django/django_orm_query.md
      - language/python/pyweb/django/django_orm_fields.md
      - language/python/pyweb/django/django_17_db_migrate.md
    - Python常用第三库:
      - language/python/pylibs/awesome_libs.md
      - language/python/pylibs/daily_libs.md
      - language/python/pylibs/apscheduler.md
      - language/python/pylibs/mlflow.md
      - language/python/pylibs/numpy.md
      - language/python/pylibs/pandas.md
      - language/python/pylibs/pathlib.md
      - language/python/pylibs/pyflink.md
      - language/python/pylibs/subprocess.md
      - language/python/pylibs/supervisor.md
      - language/python/pylibs/pickle.md
      - language/python/pylibs/collections.md
    - 开发工具与依赖管理:
      - language/python/pydevtools/env_package_selection.md
      - language/python/pydevtools/conda_usage.md
      - language/python/pydevtools/pypi_python_pkg_publish.md
      - language/python/pydevtools/pypi_source_usage.md
      - language/python/pydevtools/jupyter_tool_usage.md
      - language/python/pydevtools/py_dev_tool_selection.md
    - Python语法知识:
      - language/python/pysyntax/24_py_gc.md
      - language/python/pysyntax/23_py_gil.md
      - language/python/pysyntax/22_py_mem_manage.md
      - language/python/pysyntax/21_py_reduce.md
      - language/python/pysyntax/20_py_dir.md
      - language/python/pysyntax/19_py_property.md
      - language/python/pysyntax/18_py_oop.md
      - language/python/pysyntax/17_py_futures.md
      - language/python/pysyntax/16_py_asyncio.md
      - language/python/pysyntax/15_py_deep_copy.md
      - language/python/pysyntax/14_py_is_and_equals.md
      - language/python/pysyntax/13_py_func_params.md
      - language/python/pysyntax/12_py_iterator.md
      - language/python/pysyntax/11_py_generator.md
      - language/python/pysyntax/10_py_decorator.md
      - language/python/pysyntax/09_py_closure.md
      - language/python/pysyntax/08_py_def_and_lambda.md
      - language/python/pysyntax/07_py_exception.md
      - language/python/pysyntax/06_py_condition_and_loop.md
      - language/python/pysyntax/05_py_slices.md
      - language/python/pysyntax/04_py_list_tuple_dict.md
      - language/python/pysyntax/03_py_string.md
      - language/python/pysyntax/02_py_variable_comment.md
      - language/python/pysyntax/01_py_basics.md
  - Go编程:
    - language/golang/go_learn_docs.md
    - Go最佳实践:
      - language/golang/gobestpractices/go_code_standard.md
      - language/golang/gobestpractices/go_security_guide.md
    - 环境与依赖管理:
      - language/golang/gobestpractices/go_install_guide.md
      - language/golang/gobestpractices/go_install_guide_2.md
    - Go语法:
      - language/golang/gosyntax/go_basics.md
      - language/golang/gosyntax/go_data_struct.md
      - language/golang/gosyntax/go_data_type.md
      - language/golang/gosyntax/go_point.md
  - ModelOps:
    - 机器学习:
      - notehub/modelops/ml_basic/data_mining.md
      - notehub/modelops/ml_basic/ml_term.md
      - notehub/modelops/ml_basic/ml_work_flow.md
      - notehub/modelops/ml_basic/model_evalution.md
  - 综合知识库:
    - index: notehub/index.md
    - 编程内功:
      - 数据结构与算法:
        - notehub/codecore/data_struct/codecore_learn_docs.md
        - notehub/codecore/data_struct/why_learn_datastruct.md
        - notehub/codecore/data_struct/datastruct_understanding.md
        - notehub/codecore/data_struct/datastruct_algo_summary.md
        - notehub/codecore/data_struct/big_O.md
        - 数据结构:
          - notehub/codecore/data_struct/datastruct_array.md
          - notehub/codecore/data_struct/datastruct_array_skill.md
          - notehub/codecore/data_struct/datastruct_equeue.md
          - notehub/codecore/data_struct/datastruct_list.md
          - notehub/codecore/data_struct/datastruct_stack.md
        - 常用算法:
          - notehub/codecore/data_struct/algo_recursion.md
          - notehub/codecore/data_struct/algo_sort.md
      - 设计模式:
        - notehub/codecore/design_patterns/design_patterns_categories.md
        - notehub/codecore/design_patterns/object_oriented_principles.md
    - 软件工程:
      - notehub/software_engineering/capacity_manage.md
      - notehub/software_engineering/encrypt_and_decrypt.md
      - notehub/software_engineering/algo_hash.md
      - notehub/software_engineering/auth_jwt.md
      - notehub/software_engineering/gRPC.md
      - notehub/software_engineering/rpc_learn.md
      - notehub/software_engineering/api_desgin.md
      - notehub/software_engineering/middle_platform_and_platform.md
      
    - 云计算技术:
      - K8S:
        - notehub/cloud/k8s/kubernetes_deploy.md
        - notehub/cloud/k8s/yaml_usage.md
        - notehub/cloud/k8s/k8s_core_name.md
        - notehub/cloud/k8s/k8s_cluster_deploy.md
        - notehub/cloud/k8s/k8s_common_cmd.md
        - notehub/cloud/k8s/k8s_usage_skills.md
        - notehub/cloud/k8s/k8s_private_hub_pull_image.md
        - notehub/cloud/k8s/k8s_common_qa.md
        - notehub/cloud/k8s/k8s_ectd_mount_memo.md
        - notehub/cloud/k8s/k8s_storageclass_nfs.md
        - notehub/cloud/k8s/k8s_dashboard.md
      - Docker:
        - notehub/cloud/docker/docker_detail_commands.md
        - notehub/cloud/docker/dockerignore_template.md
        - notehub/cloud/docker/docker_registry_usage.md
        - notehub/cloud/docker/dockerifle_guide.md
        - notehub/cloud/docker/docker_common_software_install.md
        - notehub/cloud/docker/docker_practical_skills.md
        - notehub/cloud/docker/docker_command.md
        - notehub/cloud/docker/docker_install_guide.md
        - notehub/cloud/docker/docker_arch_and_principle.md
      - Docker-Compose:
        - notehub/cloud/docker_compose/docker_compose_summary.md
        - notehub/cloud/docker_compose/docker_compose_software_usage.md
    - 大数据技术:
      - Spark:
        - notehub/bigdata/spark/spark_first_know.md
        - notehub/bigdata/spark/spark_rdd.md
        - notehub/bigdata/spark/spark_shuffle.md
        - notehub/bigdata/spark/spark_distribute_compute.md
        - notehub/bigdata/spark/spark_scheduler_system.md
  - 常用工具:
    - toolhub/ai_tools.md
    - toolhub/selections.md
    - 常用软件安装:
      - toolhub/software_install/java.md
      - toolhub/software_install/nginx.md
      - toolhub/software_install/postgresql.md
      - toolhub/software_install/mongodb.md
      - toolhub/software_install/rabbitmq.md
      - toolhub/software_install/redis.md
      - toolhub/software_install/etcd.md
      - toolhub/software_install/kafka.md
      - toolhub/software_install/zookeeper.md
      - toolhub/software_install/hadoop.md
      - toolhub/software_install/YARN.md
      - toolhub/software_install/spark_on_yarn.md
      - toolhub/software_install/flink_on_yarn.md
      - toolhub/software_install/zabbix.md
    - 常用软件使用:
      - toolhub/software_usage/git_common_install.md
      - toolhub/software_usage/git_config.md
      - toolhub/software_usage/git_install_for_centos7.md
      - toolhub/software_usage/git_multi_ssh.md
      - toolhub/software_usage/git_usage_summary.md
      - toolhub/software_usage/gitflow_usage.md
      - toolhub/software_usage/github_access_acce.md
      - toolhub/software_usage/macos_common_quickly_key.md
      - toolhub/software_usage/vim_usage.md
  - 迎刃而解:
    - index: solutionhub/index.md
    - BugHub:
      - solutionhub/bughub/jupyter_matplotlib_font_bug.md
      - solutionhub/bughub/jupyter_asyncio_run_bug.md
      - solutionhub/bughub/rsa_encryption_bug.md
      - solutionhub/bughub/conda_rename_env_bug.md
      - solutionhub/bughub/window_install_pip_bug.md
      - solutionhub/bughub/jupyterhub_deploy_bug.md
    - OpsHub:
      - solutionhub/opshub/mac_brew_service_error_solution.md
      - solutionhub/opshub/win10_git_chinese_solution.md
      - solutionhub/opshub/centos_yum_source_delete_solution.md
      - solutionhub/opshub/server_disk_full_solution.md
  - 随思录:
    - index: thinking/index.md
    - thinking/article/learn_top_down_or_bottom_up.md
    - thinking/article/personal_strategy_focus_and_abandonment.md
    - thinking/article/the_wisdom_of_asking_questions.md
    - thinking/article/how_to_learn_open_source_project.md
    - thinking/article/tech_yiyan.md
    - thinking/article/how_to_do_things_clearly.md
    - thinking/article/here_we_go.md
    
  - 标签: tag.md
  
  # - 留言板: liuyanban.md
  # - 友链:  #     - 友链: about/link.md

